services:
  notification-service:
    build: .
    container_name: notification-service
    ports:
      - "${PORT:-6752}:${PORT:-6752}"
    env_file:
      - .env.prod
    environment:
      - DEV_ENV=production
    networks:
      - hendrius_network

networks:
  hendrius_network:
    external: true
